/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddContactsForm: typeof import('./src/components/contacts/AddContactsForm.vue')['default']
    AddFileInProjectStage: typeof import('./src/components/gallery/modals/AddFileInProjectStage.vue')['default']
    AddProjectStage: typeof import('./src/components/gallery/modals/AddProjectStage.vue')['default']
    AlbumInfo: typeof import('./src/components/gallery/AlbumInfo.vue')['default']
    AppAlert: typeof import('./src/components/ui/AppAlert.vue')['default']
    AppButton: typeof import('./src/components/ui/AppButton.vue')['default']
    AppDropdown: typeof import('./src/components/ui/AppDropdown.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    AppModal: typeof import('./src/components/ui/AppModal.vue')['default']
    AppModal2: typeof import('./src/components/ui/AppModal2.vue')['default']
    AppPageContainer: typeof import('./src/components/layout/AppPageContainer.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    BaseBtn: typeof import('./src/components/base/BaseBtn.vue')['default']
    BaseCard: typeof import('./src/components/base/BaseCard.vue')['default']
    BaseCardDropdown: typeof import('./src/components/base/BaseCardDropdown.vue')['default']
    BaseInput: typeof import('./src/components/base/BaseInput.vue')['default']
    BaseUpload: typeof import('./src/components/base/BaseUpload.vue')['default']
    CatalogItem: typeof import('./src/components/company/catalog/CatalogItem.vue')['default']
    CommentForm: typeof import('./src/components/projects/stages/commnets/CommentForm.vue')['default']
    CompanyCatalog: typeof import('./src/components/company/CompanyCatalog.vue')['default']
    CompanyPriceList: typeof import('./src/components/company/CompanyPriceList.vue')['default']
    ContactsList: typeof import('./src/components/contacts/ContactsList.vue')['default']
    FormDatepicker: typeof import('./src/components/form/inputs/FormDatepicker.vue')['default']
    FormInput: typeof import('./src/components/form/inputs/FormInput.vue')['default']
    FormLocationSearch: typeof import('./src/components/form/inputs/FormLocationSearch.vue')['default']
    FormSelect: typeof import('./src/components/form/inputs/FormSelect.vue')['default']
    GalleryAlbum: typeof import('./src/components/gallery/GalleryAlbum.vue')['default']
    GalleryAlbumsList: typeof import('./src/components/gallery/GalleryAlbumsList.vue')['default']
    GalleryModal: typeof import('./src/components/gallery/modals/GalleryModal.vue')['default']
    ImageItem: typeof import('./src/components/gallery/ImageItem.vue')['default']
    ImageListItem: typeof import('./src/components/gallery/ImageListItem.vue')['default']
    NotificationPopup: typeof import('./src/components/notifications/NotificationPopup.vue')['default']
    NotoficationBtn: typeof import('./src/components/notifications/NotoficationBtn.vue')['default']
    PriceItem: typeof import('./src/components/company/catalog/PriceItem.vue')['default']
    ProjectCard: typeof import('./src/components/projects/ProjectCard.vue')['default']
    ProjectFiles: typeof import('./src/components/projects/ProjectFiles.vue')['default']
    ProjectList: typeof import('./src/components/projects/ProjectList.vue')['default']
    ProjectModal: typeof import('./src/components/gallery/modals/ProjectModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StageBid: typeof import('./src/components/projects/stages/stage-tabs/StageBid.vue')['default']
    StageComments: typeof import('./src/components/projects/stages/stage-tabs/StageComments.vue')['default']
    StageFiles: typeof import('./src/components/projects/stages/stage-tabs/StageFiles.vue')['default']
    StageInfo: typeof import('./src/components/projects/stages/stage-tabs/StageInfo.vue')['default']
    StageItem: typeof import('./src/components/projects/stages/StageItem.vue')['default']
    StageList: typeof import('./src/components/projects/stages/StageList.vue')['default']
    StageTabs: typeof import('./src/components/projects/stages/StageTabs.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UForm: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UNavigationMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UpdateAlbumModal: typeof import('./src/components/gallery/modals/UpdateAlbumModal.vue')['default']
    UpdateMediaModal: typeof import('./src/components/gallery/modals/UpdateMediaModal.vue')['default']
    UploadMedia: typeof import('./src/components/gallery/modals/UploadMedia.vue')['default']
    USelect: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USlideover: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue')['default']
  }
}
